application: multi-user-blog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:       

- url: /.*
  script: project.app

- url: /css
  static_dir: static

libraries:

- name: jinja2
  version: latest