application: multi-user-blog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:       


- url: /static
  static_dir: static

- url: /blog/static
  static_dir: static

- url: /blog/(.*)
  static_dir: project.app

- url: /blog/signup
  static_dir: project.app

- url: /.*
  script: project.app


libraries:

- name: jinja2
  version: latest